### ISSUE TITLE
Question: How to do parameterized routes

### ISSUE THREAD

**Issue by LayZeeDK** [benwinding/ngext#4]
Thank you for sharing this idea with the world!

How do we create a parameterized page route using ngext?

From `pages/README.md`:

---
# PAGES

This directory contains your application *pages*.
Each page file is mapped to a url route in your application.

```
~/pages/page.ts          ->  /page
~/pages/folder/index.ts  ->  /folder
~/pages/folder/page.ts   ->  /folder/page
```

Compiled routes are found in `~/.ngext/src/routes.ts`
---

How would we do `/page/{id}`?

**Comment by benwinding** [comment]
Hi @LayZeeDK,

Thanks for checking out the project! Yes, I need to work on the documentation a bit, but for now, this is what you're looking for:

## parameterized page route
Simply putting a `:` in front of the page component filename, signifies that it is a Parametrized route, which will give you the params in `ActivatedRoute.params`
```
Page File                  Route
~/pages/user/:id.ts   ->  /folder/:id
``` 

Let me know if there's anything else you need.

Cheers,
Ben

**Comment by LayZeeDK** [comment]
Thanks for your answer! Unfortunately, `:id.ts` is an invalid filename in Windows ☹️ (Colon is not allowed)

**Comment by benwinding** [comment]
Oh no! Sorry about that, I had no idea, as I'm on Ubuntu.

Okay, I'll change it from `:` to the `_` character, like this:

```
Page File                  Route (Generated)
~/pages/user/_id.ts   ->  /folder/:id
```

Thanks for reporting the issue, and let me know if there's anything else.

Cheers,
Ben

**Comment by benwinding** [comment]
Dynamic routes now use `_` in version `0.1.0` :+1:

**Comment by LayZeeDK** [comment]
Thanks for the quick fix!

How about nested parameterized routes such as:
- `/blog/:categoryId/:articleId`
- `/catalog/:categoryId/:productId`
- `/company/:customerId/offices/:officeId`

Would it work with something like:
```
- company/
  - _customer-id.ts
  - _customer-id/
    - offices/
      - _office-id.ts
```

**Comment by benwinding** [comment]
No worries! Yes that should work as expected. It will convert them for any amount of nested routes, like this:

```
Page File                                               Route (Generated)
~/pages/company/_customer-id/office/_office-id.ts   ->  /company/:customer-id/office/:office-id
```

Then you can access those params in the `ActivatedRoute` on the page component.

**Comment by LayZeeDK** [comment]
Leaving this as closed. Thank you for the support!
